@startuml "開発周り"

title "開発周り環境概略"


package ローカル開発環境 {
    (Visual Studio 2022) as vs2022
    (Git) as git
    (GitHub Desktop) as githubdesktop
    (SQLServer Management Studio) as SSMS
}

package Azure {
    (SQL Database) as DB
    (App Service) as appservice
}

package GitHub {
    (Saikyo-Playlistリポジトリ) as remote
    (GitHub Actions) as githubActions
}

githubdesktop -up-> git : GUIで管理
vs2022 -> git : コード変更をローカル環境にプッシュ
git --> remote : コード変更をリモート環境にプッシュ
remote --> vs2022 : コード内容を複製


githubActions -> remote : mainブランチ内容を取得
githubActions --> appservice : mainブランチをデプロイ

vs2022 --> DB : 参照
SSMS --> DB : 参照・管理 
appservice --> DB : 参照

@enduml

